/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 0bf46522ae1ad0b7e7379389100545a1)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "CodeGeneratorAgent" | "UserAppSandboxService" | "DORateLimitStore" | "UserSecretsStore" | "SpaceDO" | "ThinkAgent";
	}
	interface Env {
		VibecoderStore: KVNamespace;
		TEMPLATES_BUCKET: R2Bucket;
		DB: D1Database;
		DISPATCHER: DispatchNamespace;
		ARTIFACTS: Artifacts;
		LOADER: WorkerLoader;
		BROWSER: Fetcher;
		AI: Ai;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;
		TEMPLATES_REPOSITORY: "https://github.com/cloudflare/vibesdk-templates";
		DISPATCH_NAMESPACE: "vibesdk-default-namespace";
		ARTIFACTS_NAMESPACE: "vibesdk-production";
		PLATFORM_CAPABILITIES: {"features":{"app":{"enabled":true},"presentation":{"enabled":false},"general":{"enabled":false}},"version":"1.0.0"};
		MAX_SANDBOX_INSTANCES: "10";
		SANDBOX_INSTANCE_TYPE: "standard-3";
		DEV_BROWSER_SIDECAR_URL: "http://127.0.0.1:9223";
		DEV_BROWSER_PREVIEW_ORIGIN: "http://localhost:5173";
		CUSTOM_DOMAIN: string;
		ENVIRONMENT: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_AI_GATEWAY_TOKEN: string;
		CLOUDFLARE_AI_GATEWAY: string;
		GITHUB_EXPORTER_CLIENT_ID: string;
		GITHUB_EXPORTER_CLIENT_SECRET: string;
		JWT_SECRET: string;
		BENCHMARK_MODE: string;
		CF_OAUTH_ENCRYPTION_KEY: string;
		CLOUDFLARE_OAUTH_CLIENT_ID: string;
		CLOUDFLARE_OAUTH_CLIENT_SECRET: string;
		ENABLE_CLOUDFLARE_LIMITS: string;
		ENABLE_MODE_SWITCHER: string;
		ENABLE_USER_ACCOUNT_DEPLOY: string;
		CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
		Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
		DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
		UserSecretsStore: DurableObjectNamespace<import("./worker/index").UserSecretsStore>;
		THINK_DO: DurableObjectNamespace<import("./worker/index").ThinkAgent>;
		SPACE_DO: DurableObjectNamespace<import("./worker/index").SpaceDO>;
		API_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "DISPATCH_NAMESPACE" | "ARTIFACTS_NAMESPACE" | "PLATFORM_CAPABILITIES" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE" | "DEV_BROWSER_SIDECAR_URL" | "DEV_BROWSER_PREVIEW_ORIGIN" | "CUSTOM_DOMAIN" | "ENVIRONMENT" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_AI_GATEWAY_TOKEN" | "CLOUDFLARE_AI_GATEWAY" | "GITHUB_EXPORTER_CLIENT_ID" | "GITHUB_EXPORTER_CLIENT_SECRET" | "JWT_SECRET" | "BENCHMARK_MODE" | "CF_OAUTH_ENCRYPTION_KEY" | "CLOUDFLARE_OAUTH_CLIENT_ID" | "CLOUDFLARE_OAUTH_CLIENT_SECRET" | "ENABLE_CLOUDFLARE_LIMITS" | "ENABLE_MODE_SWITCHER" | "ENABLE_USER_ACCOUNT_DEPLOY">> {}
}
declare module "*.md" {
	const value: string;
	export default value;
}
declare module "*.md?raw" {
	const value: string;
	export default value;
}