/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: beed0c1dd3e38110bfb6b0b6eee7f54e)
interface __BaseEnv_Env {
  ARTIFACTS_ACCOUNT_ID: string;
  ARTIFACTS_NAMESPACE: string;
  ARTIFACTS_API_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker/index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
